#!/usr/bin/env python3

import sys
sys.path.append('src')

from data_loader import DataLoader
from config.config import RAW_DATA_DIR, PROCESSED_DATA_DIR
import os

def save_all_processed_content():
    """Save the full processed content of all documents to separate files"""
    
    loader = DataLoader(RAW_DATA_DIR)
    documents = loader.load_documents_from_directory()
    
    if not documents:
        print("❌ No documents found!")
        return
    
    print(f"💾 Saving full content for {len(documents)} documents")
    print("=" * 60)
    
    # Create output directory
    output_dir = PROCESSED_DATA_DIR / "full_content"
    output_dir.mkdir(exist_ok=True)
    
    for i, doc in enumerate(documents):
        # Create filename for processed content
        original_name = doc['filename']
        name_without_ext = os.path.splitext(original_name)[0]
        output_filename = f"{name_without_ext}_processed.txt"
        output_path = output_dir / output_filename
        
        # Save full content to file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(f"PROCESSED DOCUMENT: {original_name}\n")
            f.write(f"Source: {doc['source']}\n")
            f.write(f"File Type: {doc['file_type']}\n")
            f.write(f"Content Length: {len(doc['content'])} characters\n")
            f.write(f"Word Count: {len(doc['content'].split())} words\n")
            f.write("=" * 80 + "\n")
            f.write("FULL CONTENT:\n")
            f.write("=" * 80 + "\n")
            f.write(doc['content'])
            f.write("\n" + "=" * 80 + "\n")
            f.write("END OF DOCUMENT\n")
        
        print(f"✅ Saved: {output_filename}")
        print(f"   Location: {output_path}")
        print(f"   Size: {len(doc['content'])} characters")
    
    # Also create a combined file with all documents
    combined_path = output_dir / "all_documents_combined.txt"
    with open(combined_path, 'w', encoding='utf-8') as f:
        f.write("COMBINED PROCESSED DOCUMENTS\n")
        f.write(f"Total Documents: {len(documents)}\n")
        f.write("Generated by VirtuaIntelligence RAG System\n")
        f.write("=" * 100 + "\n\n")
        
        for doc in documents:
            f.write(f"\n{'='*20} DOCUMENT: {doc['filename']} {'='*20}\n")
            f.write(f"Source: {doc['source']}\n")
            f.write(f"Type: {doc['file_type']}\n")
            f.write(f"Length: {len(doc['content'])} chars\n")
            f.write("-" * 80 + "\n")
            f.write(doc['content'])
            f.write("\n" + "-" * 80 + "\n\n")
    
    print(f"\n✅ Combined file created: all_documents_combined.txt")
    print(f"📂 All files saved in: {output_dir}")
    
    # Summary
    total_chars = sum(len(doc['content']) for doc in documents)
    print(f"\n📊 Summary:")
    print(f"Total files created: {len(documents) + 1}")
    print(f"Total content saved: {total_chars:,} characters")
    print(f"Output directory: data/processed/full_content/")

if __name__ == "__main__":
    save_all_processed_content()